#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
    systemctl daemon-reload || true
    systemctl enable pardus-thermal-guard.service || true
    systemctl start pardus-thermal-guard.service || true
fi
#DEBHELPER#
exit 0
